/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SiteUser = {
  _id: string;
  _type: "siteUser";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  email?: string;
  name?: string;
  status?: "pending" | "approved" | "denied";
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  strainType?: "sativa" | "hybrid" | "indica";
  price?: number;
  thcPercent?: number;
  cbdPercent?: number;
  description?: string;
  effects?: Array<string>;
  media?: Array<
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
        };
        media?: unknown;
        caption?: string;
        _type: "file";
        _key: string;
      }
  >;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | SiteUser
  | Product
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: src/sanity/lib/queries.ts
// Variable: ALL_PRODUCTS_QUERY
// Query: *[_type == "product"] | order(name asc) {    _id,    _type,    name,    strainType,    price,    thcPercent,    cbdPercent,    quantity,    description,    effects,    "media": media[] {      _type,      _key,      alt,      caption,      "url": asset->url,      "mimeType": asset->mimeType    }  }
export type ALL_PRODUCTS_QUERY_RESULT = Array<{
  _id: string;
  _type: "product";
  name: string | null;
  strainType: "hybrid" | "indica" | "sativa" | null;
  price: number | null;
  thcPercent: number | null;
  cbdPercent: number | null;
  quantity: null;
  description: string | null;
  effects: Array<string> | null;
  media: Array<
    | {
        _type: "file";
        _key: string;
        alt: null;
        caption: string | null;
        url: string | null;
        mimeType: string | null;
      }
    | {
        _type: "image";
        _key: string;
        alt: string | null;
        caption: null;
        url: string | null;
        mimeType: string | null;
      }
  > | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: PRODUCT_BY_ID_QUERY
// Query: *[_type == "product" && _id == $id][0] {    _id,    _type,    name,    strainType,    price,    thcPercent,    cbdPercent,    quantity,    description,    effects,    "media": media[] {      _type,      _key,      alt,      caption,      "url": asset->url,      "mimeType": asset->mimeType    }  }
export type PRODUCT_BY_ID_QUERY_RESULT = {
  _id: string;
  _type: "product";
  name: string | null;
  strainType: "hybrid" | "indica" | "sativa" | null;
  price: number | null;
  thcPercent: number | null;
  cbdPercent: number | null;
  quantity: null;
  description: string | null;
  effects: Array<string> | null;
  media: Array<
    | {
        _type: "file";
        _key: string;
        alt: null;
        caption: string | null;
        url: string | null;
        mimeType: string | null;
      }
    | {
        _type: "image";
        _key: string;
        alt: string | null;
        caption: null;
        url: string | null;
        mimeType: string | null;
      }
  > | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: PRODUCTS_BY_STRAIN_QUERY
// Query: *[_type == "product" && strainType == $strainType] | order(name asc) {    _id,    name,    strainType,    price,    thcPercent,    cbdPercent,    "primaryImage": media[_type == "image"][0] {      alt,      "url": asset->url    }  }
export type PRODUCTS_BY_STRAIN_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  strainType: "hybrid" | "indica" | "sativa" | null;
  price: number | null;
  thcPercent: number | null;
  cbdPercent: number | null;
  primaryImage: {
    alt: string | null;
    url: string | null;
  } | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: ALL_SITE_USERS_QUERY
// Query: *[_type == "siteUser"] | order(_createdAt desc) {    _id,    email,    name,    status,    _createdAt  }
export type ALL_SITE_USERS_QUERY_RESULT = Array<{
  _id: string;
  email: string | null;
  name: string | null;
  status: "approved" | "denied" | "pending" | null;
  _createdAt: string;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "product"] | order(name asc) {\n    _id,\n    _type,\n    name,\n    strainType,\n    price,\n    thcPercent,\n    cbdPercent,\n    quantity,\n    description,\n    effects,\n    "media": media[] {\n      _type,\n      _key,\n      alt,\n      caption,\n      "url": asset->url,\n      "mimeType": asset->mimeType\n    }\n  }\n': ALL_PRODUCTS_QUERY_RESULT;
    '\n  *[_type == "product" && _id == $id][0] {\n    _id,\n    _type,\n    name,\n    strainType,\n    price,\n    thcPercent,\n    cbdPercent,\n    quantity,\n    description,\n    effects,\n    "media": media[] {\n      _type,\n      _key,\n      alt,\n      caption,\n      "url": asset->url,\n      "mimeType": asset->mimeType\n    }\n  }\n': PRODUCT_BY_ID_QUERY_RESULT;
    '\n  *[_type == "product" && strainType == $strainType] | order(name asc) {\n    _id,\n    name,\n    strainType,\n    price,\n    thcPercent,\n    cbdPercent,\n    "primaryImage": media[_type == "image"][0] {\n      alt,\n      "url": asset->url\n    }\n  }\n': PRODUCTS_BY_STRAIN_QUERY_RESULT;
    '\n  *[_type == "siteUser"] | order(_createdAt desc) {\n    _id,\n    email,\n    name,\n    status,\n    _createdAt\n  }\n': ALL_SITE_USERS_QUERY_RESULT;
  }
}
